### ISSUE TITLE
PB-0029 Pesquisar Frameworks

### ISSUE THREAD

**Issue by Claudia-Nunes** [ScrumerDataAPI/API#27]
# Descrição da Atividade

- [ ] Pesquisar aplicações e gerar novas Tarefas dos seguintes Frameworks

1. `Bootstap`
2. `React`
3. `Express JS`
4. `Django`
5. `Ruby on Rails`
6. `Laravel`
7. `Spring`
8. `Angular`
9. `Vue JS`
10. `Ember JS`
11. `Asp.Net`

**Comment by Lemos05** [comment]
Pesquisei sobre a ferramenta Bootstrap e da para gerar um comando de "próxima página" e "anterior" através de uma imagem de seta. @DanielleSismon favor criar duas tarefas.

1. tarefa de aplicação do Bootstrap CSS
2. tarefa de aplicação do Bootstrap HTML
3. tarefa de aplicação de imagem no layout do Figma
